# Site settings
title: OpenChurch
email: openchurchsite@gmail.com
url: http://openchurchsite.com/
description: "The OpenChurch distribution is for churches and ministries. It is a flexible platform with common features for churches that can help streamline development of these websites."
skills: "Open source - Drupal CMS - Churches & Ministries"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8fa68e
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 47423c
  secondary-dark: d17c29

# Footer settings
footer:
  copyright: OpenChurchSite.com

# Build settings
markdown: kramdown
permalink: pretty
